apiVersion: apps/v1
kind: Deployment
metadata:
  name: openjdk-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openjdk
  template:
    metadata:
      labels:
        app: openjdk
    spec:
      containers:
      - name: openjdk-container
        image: openjdk:21-jdk-slim
        ports:
        - containerPort: 8989  # 假设应用监听 8080 端口（按需修改）
        command: ["sleep", "infinity"]  # 保持容器运行（仅测试用）
