apiVersion: v1
kind: Service
metadata:
  name: openjdk-service
  namespace: default
spec:
  selector:
    app: openjdk  # 匹配 Deployment 的标签
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8989  # 与 Deployment 的 containerPort 一致
  type: NodePort  # 方便本地访问（或 LoadBalancer/ClusterIP）
